---
name: CI

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
  push:
    branches: [andyg.github-actions-ci] # XXX

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  github_env:
    name: GitHub Env Debug
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        run: echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

  build_win:
    name: Windows
    runs-on: windows-2022
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.*'
          host: windows
          target: desktop
          arch: win64_msvc2022_arm64_cross_compiled

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build metadata
        run: |
          echo ("GIT_SHORT_SHA=" + (git rev-parse --short $env:GITHUB_SHA)) >> $env:GITHUB_ENV
          echo ("GIT_BRANCH=" + $env:GITHUB_REF.replace('refs/heads/', '')) >> $env:GITHUB_ENV
          echo ("VERSION=" + (Get-Content app/version.txt)) >> $env:GITHUB_ENV

        # Copy-Item -Path "build-x64-release\app\release\Moonlight.exe -Destination" "artifacts\Moonlight-$($env:VERSION)-$($env:GIT_BRANCH)-$($env:GIT_SHORT_SHA).exe"
      - name: Build Windows
        shell: pwsh
        run: |
          scripts\build-arch.bat Release
          mkdir artifacts
          echo ("Copy-Item -Path build\installer-x64-release\MoonlightPortable-x64-$($env:VERSION).zip -Destination artifacts\MoonlightPortable-x64-$($env:VERSION)-$($env:GIT_BRANCH)-$($env:GIT_SHORT_SHA).zip")
          Copy-Item -Path "build\installer-x64-release\MoonlightPortable-x64-$($env:VERSION).zip" -Destination "artifacts\MoonlightPortable-x64-$($env:VERSION)-$($env:GIT_BRANCH)-$($env:GIT_SHORT_SHA).zip"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: moonlight-windows
          path: artifacts/
