---
name: CI

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
  push:
    branches: [andyg.github-actions-ci] # XXX

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build_win:
    name: Windows
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Qt x64
        uses: jurplel/install-qt-action@v4
        with:
          arch: win64_msvc2022_64
          dir: ${{ github.workspace }}\x64\
          host: windows
          setup-python: false
          target: desktop
          version: '6.8.*'

      - name: Setup metadata
        run: |
          echo ("GIT_SHORT_SHA=" + (git rev-parse --short $env:GITHUB_SHA)) >> $env:GITHUB_ENV
          echo ("GIT_BRANCH=" + $env:GITHUB_REF.replace('refs/heads/', '')) >> $env:GITHUB_ENV
          echo ("VERSION=" + (Get-Content app/version.txt)) >> $env:GITHUB_ENV
          echo ("OLDPATH=" + $env.PATH) >> $env.GITHUB_ENV

      - name: Build Windows x64
        shell: pwsh
        run: |
          echo "$($env.OLDPATH)"
          $env:PATH = "$($env:QT_ROOT_DIR)\bin;$($env:OLDPATH)"
          scripts\build-arch.bat Release
          mkdir artifacts
          Copy-Item "build\installer-x64-release\MoonlightPortable-x64-$($env:VERSION).zip" -Destination "artifacts\MoonlightPortable-x64-$($env:VERSION)-$($env:GIT_BRANCH)-$($env:GIT_SHORT_SHA).zip"
          Copy-Item "build\symbols-x64-Release\MoonlightDebuggingSymbols-x64-$($env:VERSION).zip" -Destination "artifacts\MoonlightDebuggingSymbols-x64-$($env:VERSION)-$($env:GIT_BRANCH)-$($env:GIT_SHORT_SHA).zip"
          Get-ChildItem -Path "artifacts\" -Recurse

      - name: Install Qt arm64
        uses: jurplel/install-qt-action@v4
        with:
          arch: win64_msvc2022_arm64_cross_compiled
          dir: ${{ github.workspace }}\arm64\
          host: windows
          setup-python: false
          target: desktop
          version: '6.8.*'

      - name: Build Windows arm64
        shell: pwsh
        run: |
          Copy-Item "scripts\appveyor\qmake.bat" -Destination "$($env:QT_ROOT_DIR)\bin\"
          Copy-Item "scripts\appveyor\qtpaths.bat" -Destination "$($env:QT_ROOT_DIR)\bin\"
          Copy-Item "scripts\appveyor\target_qt.conf -Destination "$($env:QT_ROOT_DIR)\bin\"
          $env:PATH = "$($env:OLDPATH);$($env:QT_ROOT_DIR)\bin"
          scripts\build-arch.bat Release
          mkdir artifacts
          Copy-Item "build\installer-arm64-release\MoonlightPortable-arm64-$($env:VERSION).zip" -Destination "artifacts\MoonlightPortable-arm64-$($env:VERSION)-$($env:GIT_BRANCH)-$($env:GIT_SHORT_SHA).zip"
          Copy-Item "build\symbols-arm64-Release\MoonlightDebuggingSymbols-arm64-$($env:VERSION).zip" -Destination "artifacts\MoonlightDebuggingSymbols-arm64-$($env:VERSION)-$($env:GIT_BRANCH)-$($env:GIT_SHORT_SHA).zip"
          Get-ChildItem -Path "artifacts\" -Recurse
          # -- Build universal binary bundle
          scripts\generate-bundle.bat Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: moonlight-windows
          path: artifacts/
